// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPMCZbAQ01VouGV6jsXtpthEgKWQ10bIE',
    appId: '1:224663469548:web:172b4c30202bcdd8b994c9',
    messagingSenderId: '224663469548',
    projectId: 'shop-a4697',
    authDomain: 'shop-a4697.firebaseapp.com',
    storageBucket: 'shop-a4697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8wwXWnPnHp_UGlpIrKLpjTTpowUJm89M',
    appId: '1:224663469548:android:d8a929034491b3dfb994c9',
    messagingSenderId: '224663469548',
    projectId: 'shop-a4697',
    storageBucket: 'shop-a4697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIm0ckjz_GCAojQllGn9msEDQ3OTrD-Y',
    appId: '1:224663469548:ios:5cebd81a359c8786b994c9',
    messagingSenderId: '224663469548',
    projectId: 'shop-a4697',
    storageBucket: 'shop-a4697.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIm0ckjz_GCAojQllGn9msEDQ3OTrD-Y',
    appId: '1:224663469548:ios:26f56095893f88e2b994c9',
    messagingSenderId: '224663469548',
    projectId: 'shop-a4697',
    storageBucket: 'shop-a4697.appspot.com',
    iosBundleId: 'com.example.shop.RunnerTests',
  );
}
